### ISSUE TITLE
schema with allOf does not validate if type is not specified as well.

### ISSUE THREAD

**Issue by akdor1154** [apigee-127/sway#144]
```yaml
paths:
  /allOf:
    get:
      responses:
        200:
          description: a route which returns objects that validate against an allOf schema
          schema:
            allOf:
              - type: object
                properties:
                  a:
                    type: number
                required: [a]
              - type: object
                properties:
                  b:
                    type: number
                required: [b]
```

returns a validation error when I try to do path.validateResponse() with `{a: 1, b:2}`
```
Invalid body: Value failed JSON Schema validation
      Expected type object but found type string
      Expected type object but found type string
```

If I add `type: object` as a sibling to `allOf` then all works fine. The Swagger 2.0 examples specifically demonstrate using `allOf` with no type.

Using latest version on NPM. Haven't tried git master but there seem to be no open issues to do with this.

**Comment by whitlockjc** [comment]
All JSON Schema validation in sway is handled by [z-schema](https://github.com/zaggino/z-schema)  I'm not sure if the issue is with sway or z-schema but if it's purely from a JSON Schema validation perspective, I'm not sure sway is the culprit.  I'll do a quick test and see if I can create a reproduction recipe without sway.

**Comment by whitlockjc** [comment]
I cannot reproduce with sway or z-schema.  Can you give me the full error output, the objects for each validation error?  It will provide more details that I can look into.

**Comment by akdor1154** [comment]
Test case at https://github.com/akdor1154/swaggerIssue144 :)

**Comment by whitlockjc** [comment]
Your reproduction scenario, `body` is an `object` yet you're passing it in as a `string` for validation.  If I remove the `JSON.stringify` call in [your example](https://github.com/akdor1154/swaggerIssue144/blob/master/index.js#L9), it passes without validation error.  Since your parameter does not have a `type`, we cannot infer that you passed in a JSON `string` that should be coerced into an `object` so when we call the validation API in z-schema, it fails due to you giving a `string` but the schema expecting an `object` with properties.

sway is working as designed.

**Comment by akdor1154** [comment]
Thanks for the explanation. I thought the ServerResponse interface was designed to mimic that of the `http` module (where `body` is always a string or buffer, if I am not mistaken). I also thought that specifying the content-type header should be a sufficient hint to sway that the body should be `JSON.parse`d. Am I wrong on both counts here?

**Comment by whitlockjc** [comment]
All sway APIs dealing with parameters/responses will attempt to _coerce_ values appropriately.  The reason this is failing in your case is because you do not have a `type` set for your response schema.  Here is the code in question, with explanation as to why we don't treat an unset `type` as `object` or anything else: https://github.com/apigee-127/sway/blob/master/lib/helpers.js#L187  So if your schema doesn't have its `type` set, we cannot infer the proper type and just will pass on doing so.  In that case, no coercion is done and your value is validated as-is.
