### ISSUE TITLE
operation with 'null' value throws

### ISSUE THREAD

**Issue by mohsen1** [apigee-127/sway#16]
```yaml
swagger: '2.0'
info:
  version: 0.0.0  
  title: Simple API
paths:  
  /:
    get: null 
```

```
Uncaught (in promise) TypeError: Cannot read property 'parameters' of null
    at http://localhost:9000/bower_components/sway/browser/sway.js:1682:24
```

**Comment by whitlockjc** [comment]
Basically, we were wrapping a `Promise` within a `Promise` and the error thrown was not able to be caught.  We now will catch/reject all errors like this and reject it so you can handle it properly.  As discussed offline, we did not add extra checks in the sources to handle `null` and `undefined` being values for iterable objects (definitions, operations, paths, ...) because that would just allow someone to author bad Swagger documents.  At least with this approach they will know the err of their ways and can fix it.  We *should* handle invalid types for all types other than `null` and `undefined` so this *should* be all that is necessary.

**Comment by mohsen1** [comment]
:+1:
