### ISSUE TITLE
Cannot compile webpack: ERROR in ./node_modules/sway/lib/validation/validators.js Module not found: Error: Can't resolve 'swagger-schema-official/schema'

### ISSUE THREAD

**Issue by Nagato-Yuki** [apigee-127/sway#180]
In `lib/validation/validators.json` at line 31
```javascript
var swaggerSchema = require('swagger-schema-official/schema');
```

It seems like this line is preventing webpack to resolve for `schema.json` file in `swagger-schema-official` package

I fixed it by add `.json` to allow webpack to correctly resolve JSON dependency.
```javascript
var swaggerSchema = require('swagger-schema-official/schema.json');
```

**Comment by whitlockjc** [comment]
This is likely a deficiency in webpack as Node.js [module loading](https://nodejs.org/api/modules.html#modules_file_modules) treats `.json` files as requirable without the `.json` extension.  The same source base works fine _(without modification)_ in browserify as well.  I'm going to close this since it's not something I'll likely change but if you cannot find a way to make webpack work right _(configuration, loader, ...)_ it should be reopened.
