### ISSUE TITLE
Update json-refs to fix issue with trailing slash in options.jsonRefs

### ISSUE THREAD

**Issue by mohsen1** [apigee-127/sway#24]
part of swagger:

```
definitions:
  $ref: ./definitions/index.yaml 
```

jsonRefs.location value:

```
"http://localhost:9000/#/"
```

Request is made to:

```
http://localhost:9000//definitions/index.yaml 
```

**Comment by whitlockjc** [comment]
This is actually a path-loader issue so I've reported it there and I will release when it is fixed there.

**Comment by whitlockjc** [comment]
This is due to the hash in the location.  I'm updating json-refs to handle this but I will also update sway to not set `options.jsonRefs.location` improperly.

**Comment by whitlockjc** [comment]
It seems like you're setting `options.jsonRefs.location` yourself so you'll need to update https://github.com/swagger-api/swagger-editor/blob/c80708bf0ed249e9d3d30ee87880b87967efa3c1/app/scripts/services/builder.js#L53 so that you do not include the hash.  I'll update sway for the version of json-refs that handles things either way but it would be best to not have the hash in `options.jsonRefs.location` at all.
