### ISSUE TITLE
api.getPath works wrong

### ISSUE THREAD

**Issue by Santinell** [apigee-127/sway#76]
It returns only first one, which truthy for regexp.
paths:
- GET /host/{id}
  (id - string)
- POST /host/AWS
- POST /host/DO
- GET /host/labels

api.getPath for url "/host/xxx" always returns the first path, and can't find other operations.

**Comment by whitlockjc** [comment]
Well, this is likely because your `GET` is functionally equivalent to the other items _(As in `/host/{id}` would also match the other three paths)_ but I do see how static paths alongside patterned paths might not work right.  I personally wouldn't use ambiguous URIs like you have but since it's possible and allowable by OpenAPI/Swagger, I will update things to work.

**Comment by daddy-cool** [comment]
Thanks and sorry for the duplicate, don't know how I missed that 👍

**Comment by whitlockjc** [comment]
I'm actually not sure how best to do this.  We _could_ just make static paths always match over parameterized paths but I think that is somewhat naive.  For `/host/{id}` and `/host/AWS`, it's simple.  But what happens when you have multiple segments and any combination of them have both parameterized and static versions?

**Comment by Santinell** [comment]
I think algorithm should search in this order:
1) full match (static path + equal type of request (GET, POST, etc.))
2) the longest path (e.g. by `path.split('/').length`)
3) if paths have the same length and the same type of request, then first of them.

**Comment by whitlockjc** [comment]
If you want to work around this now, reorder the statics in front of their parameterized equivalent.  I'm working on an algorithm that will make this work regardless of order.

**Comment by whitlockjc** [comment]
@Santinell Can you please verify that the fix works as you wanted?  I _think_ it's pretty slick and it even handles cases we don't need to support, just in case.
