### ISSUE TITLE
api.getPath does not handle basePath for swagger-node-runner and express sub-app

### ISSUE THREAD

**Issue by CallMeLaNN** [apigee-127/sway#81]
I have this URL format: `domain.com/api/resource`
The baseUrl defined in swagger.yaml is `/api`
The express configured so that the /api is just a sub-app:

    app = express();
    apiApp = express();
    app.use('/api', apiApp);

The `SwaggerMiddleware` is then added into apiApp.

Both swagger definition and express already configured to use the `/api` basePath, but the swagger middleware bypass it by calling `next()` because the `api.getPath` return undefined in `swagger-node-runner/lib/connect_middleware.js`

Now in the `api.getPath`, [the pathOrReq.url here](https://github.com/apigee-127/sway/blob/v0.6.0/lib/types/api.js#L193) is returning only the sub path. In this case the `pathOrReq.url  = '/resource'` instead of `'/api/resource'`. Therefore the `regexp` and `isArray` return false.

I suggest we use `pathOrReq.originalUrl ` instead of `pathOrReq.url` since `originalUrl` is the full path url.

**Comment by whitlockjc** [comment]
swagger-node needs to be updated to call [api.getPath](https://github.com/apigee-127/sway/blob/master/docs/API.md#module_Sway..SwaggerApi+getPath) appropriately so that the `url` property of the object passed to the API has the proper value.  Sway will never have code in it that is server framework aware and as people write integrations that use Sway, it is their responsibility to make a Sway API call that will work.
