### ISSUE TITLE
Sample Headers and date type?

### ISSUE THREAD

**Issue by arun0009** [apigee-127/sway#98]
Is there a way to generate sample headers for response? 

Also, I had to change my spec to use date-time instead of date which is a valid format. It throws an exception unknown generator for "date". Is there a way to inject a custom generator?

**Comment by whitlockjc** [comment]
You can generate samples for any parameter or response.  If you have a header parameter, you can generate a sample.  There is no way to generate a sample header for a response but we could possibly support it.

As for date, `date` and `date-time` are valid formats when `type: string`.  As for right now, we do not expose any way to register a custom `format` because we only support the formats OpenAPI/Swagger supports.  I'm not even sure you can specify a different format but if you can, we should support registering custom generators.

**Comment by arun0009** [comment]
This is what I have in spec:

    ```
dateOfBirth:
       type: string
       format: date
```

and I get this expection : `unknown generator for "date" in /properties/applicantResponse/properties/dateOfBirth`

If I change the format to date-time, I am able to execute it successfully. So am not sure `date` is supported or am I doing something wrong?

**Comment by whitlockjc** [comment]
It looks like `date` isn't a JSON Schema `format` so we'll need to add this to the custom generators.  We already support some custom generators _(https://github.com/apigee-127/sway/blob/master/lib/validation/format-generators.js)_ and it looks like we'll be adding another one.

**Comment by whitlockjc** [comment]
I'm closing this issue since it was really two issues merged into one.  I will link this issue with the newly created issue.
